### ISSUE TITLE
Red waiting

### ISSUE THREAD

**Issue by newwide** [skrixx68/Dota2-Overlay-2.0#1]
Hi, I'm the guy that still updates the offset for the previous version.

I tried this 2.0 overlay but the scanner auto updater fails to scan and I got this Red "waiting" on screen. 
![image](https://user-images.githubusercontent.com/69209831/97774673-d7872480-1b94-11eb-8c45-ce53ea2cbb8f.png)

**Comment by skrixx68** [comment]
dota 2 had a major update, AOB changed for base address. ill push fix later

**Comment by skrixx68** [comment]
https://github.com/skrixx68/Dota2-Overlay-2.0/commit/d927e3944e97b00f34c2f8403521c83119ddf702
Should be fixed now, A testrun will be much appreciated :)

**Comment by Laszl0w** [comment]
Still not working it says "Wating"

**Comment by newwide** [comment]
Thanks, it's working now. 
![image](https://user-images.githubusercontent.com/69209831/97838600-7e95c880-1d1b-11eb-8699-2cef48ab6ed9.png)
