### ISSUE TITLE
The game just released a patch 2 days ago, does this still work in the current patch(7.30d)?

### ISSUE THREAD

**Issue by aeristhy** [skrixx68/Dota2-Overlay-2.0#3]

**Comment by aeristhy** [comment]
@skrixx68 tagging you just to be sure you see this <3

**Comment by luisgargudi** [comment]
Yes, just update offsets

**Comment by aeristhy** [comment]
@BigNotorious13 @skrixx68 Finding these offsets are really rough. I tried find them but I failed hard, do we have a program that can automatically find these offsets or a video tutorial explaining how to find them?

**Comment by SK68-ph** [comment]
https://github.com/skrixx68/Dota2-Overlay-2.0/blob/master/README.md
learn how to update offsets here

**Comment by aeristhy** [comment]
yeah i tried, but its rough. can't seems to find it

**Comment by SK68-ph** [comment]
> yeah i tried, but its rough. can't seems to find it

where are you stuck, what part

**Comment by aeristhy** [comment]
when I rescanned and tried to enter the value in 'Must end with the offsets' since I don't know the values for 'Must start with the offsets'(assuming they get updated every patch), they won't show up or either I scanned the wrong address?

**Comment by aeristhy** [comment]
Would be nice if this repo was still working https://github.com/skrixx68/Dota2-Overlay-OffsetUpdater

**Comment by SK68-ph** [comment]
> when I rescanned and tried to enter the value in 'Must end with the offsets' since I don't know the values for 'Must start with the offsets'(assuming they get updated every patch), they won't show up or either I scanned the wrong address?

the offsets always starts with 0 28 38, you dont have to add "it must end with" options, its much easier and stable

**Comment by aeristhy** [comment]
> > when I rescanned and tried to enter the value in 'Must end with the offsets' since I don't know the values for 'Must start with the offsets'(assuming they get updated every patch), they won't show up or either I scanned the wrong address?
> 
> the offsets always starts with 0 28 38, you don't have to add "it must end with" options

yep, I tried that as well it just seems to not work. I think I really did scanned the wrong address? 

Question 1: When you're finding these address, are you in a private lobby or in the demo? 
Question 2: If you're in a private lobby, does it matter which side Radiant or Dire are you in?
Question 3: Adding these values(06 10 14), already set? Like, 06 is the first scan and 10 is the second scan?

**Comment by SK68-ph** [comment]
> > > when I rescanned and tried to enter the value in 'Must end with the offsets' since I don't know the values for 'Must start with the offsets'(assuming they get updated every patch), they won't show up or either I scanned the wrong address?
> > 
> > 
> > the offsets always starts with 0 28 38, you don't have to add "it must end with" options
> 
> yep, I tried that as well it just seems to not work. I think I really did scanned the wrong address?
> 
> Question 1: When you're finding these address, are you in a private lobby or in the demo? Question 2: If you're in a private lobby, does it matter which side Radiant or Dire are you in? Question 3: Adding these values(06 10 14), already set? Like, 06 is the first scan and 10 is the second scan?

Q1. Yes i test it with "Practice with bots"/"Custom Lobbies" either is fine.
Q2. Yes it does matter, for radiant the value of isNOTVisibleByEnemy address is = 6. for dire the value is 10, else if you are visiblebyenemy the value is always 14
Q3.  NO. each of that value is a STATE. this states define if you are visible by enemy or not like i said in Q2.

**Comment by aeristhy** [comment]
> > > > when I rescanned and tried to enter the value in 'Must end with the offsets' since I don't know the values for 'Must start with the offsets'(assuming they get updated every patch), they won't show up or either I scanned the wrong address?
> > > 
> > > 
> > > the offsets always starts with 0 28 38, you don't have to add "it must end with" options
> > 
> > 
> > yep, I tried that as well it just seems to not work. I think I really did scanned the wrong address?
> > Question 1: When you're finding these address, are you in a private lobby or in the demo? Question 2: If you're in a private lobby, does it matter which side Radiant or Dire are you in? Question 3: Adding these values(06 10 14), already set? Like, 06 is the first scan and 10 is the second scan?
> 
> Q1. Yes i test it with "Practice with bots"/"Custom Lobbies" either is fine. Q2. Yes it does matter, for radiant the value of isNOTVisibleByEnemy address is = 6. for dire the value is 10, else if you are visiblebyenemy the value is always 14 Q3. NO. each of that value is a STATE. this states define if you are visible by enemy or not like i said in Q2.

I see, thank you so much for these informations! _I noticed you're from Philippines too. well, hello comrade_

**Comment by SK68-ph** [comment]
you can actually update the offsets under 1 minute using this method
[https://i.ibb.co/tMv0m3V/ce.png](url)
most of the time, when there's only a minor patch, only the last offset or the 5th offset gets changed.
you can try changing the offsets value using the arrow then check the value in the upper right if its the one your looking for( isVisibleByEnemy State).

**Comment by aeristhy** [comment]
I see, this is quite interesting thank you for the informations! One more thing, the offset updater, does it get/find/scan offsets automatically? or do we have program that can get/find offsets?

**Comment by SK68-ph** [comment]
> I see, this is quite interesting thank you for the informations! One more thing, the offset updater, does it get/find/scan offsets automatically? or do we have program that can get/find offsets?

no, its for fetching the latest offset posted on pastebin then overwriting the old offset. its a shit workaround hahaha. 
but maybe ill try to make an actual offset dumper

**Comment by aeristhy** [comment]
> > I see, this is quite interesting thank you for the informations! One more thing, the offset updater, does it get/find/scan offsets automatically? or do we have program that can get/find offsets?
> 
> no, its for fetching the latest offset posted on pastebin then overwriting the old offset. its a shit workaround hahaha. 
> but maybe ill try to make an actual offset dumper

yeah, I've checked the codes and I noticed. Yeah that would be very nice, I'll be looking forward to the offset dumper, I'll be following you. Thank you so much for your time!

**Comment by luisgargudi** [comment]
Hey Skrixx I was wondering if you know how to get the entity list? I cannot find it

**Comment by SK68-ph** [comment]
> Hey Skrixx I was wondering if you know how to get the entity list? I cannot find it

https://github.com/LWSS/McDota - try this it makes full use of Source 2 sdk, entity list should also be included in that project
